services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: two-buttons-app
    restart: unless-stopped
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json